# docker run --rm -it -v $PWD/..:$PWD -w $PWD ebvien/vue-cli vue create zistpak
version: "3.3"
services:
  app:
    image: node
    # command: sh -c "[[ -d ./node_modules ]] || npm install && npm run serve"
    # command: npm run serve
    # command: npm run build
    # command: npm install
    working_dir: /home/node
    volumes:
      - .:/home/node
    # ports:
    #   - "8080:8080"
    # networks:
    #   - mdb
  
#   mdb:
#     image: mongo
#     volumes:
#       - ./db:/data/db

# networks:
#   mdb:
#     external:
#       name: db
